### PR TITLE
Better order of UMD

### PR DESCRIPTION
**Pull request by YaaL**

### CODE REVIEW

**Comment by getify** [comment]
what's the purpose of re-ordering?

**Comment by YaaL** [comment]
The standard UMD is AMD first, CommonJS later and fall back to browser globals.
Your UMD definition is inverted, which doesn't play nicely with requirejs in some (possibly rather obscure) situations.

**Comment by getify** [comment]
> Your UMD definition is inverted

The UMD form is intentionally modified so as to support the typical usage pattern of polyfilling, as noted by this comment:

> // special form of UMD for polyfilling across evironments

Typo aside, the intent is to always first change the "browser globals" via context[name], and then in addition return that value in one of the module environments (AMD, CommonJS). Honestly, I've debated not even having a UMD for this polyfill, as polyfills are by definition not modularized.

> which doesn't play nicely with requirejs

This is definitely not the first time that requirejs's brittleness has caused issues. It's frustrating that their approach means you're restricted from doing things you want to do. Thankfully, requirejs (and AMD) usage are going to be on the decline.

-----

I'm not sure I understand what could happen differently if you reverse the two `else if` conditions, but I don't feel strongly either way. However, I don't want to do a patch release just for this nuanced change. So I'll leave this open to remind me to fix this the next time there's a change necessary to NPO.

**Comment by YaaL** [comment]
I agree with pulling the globals to the top (because you have it outside the conditional), it's just the order of AMD & CommonJS that causes me problems.
Like I said, it's probably rather obscure: I'm building a library that uses requirejs and almond internally, it has to include npo (pulling it outside is not an option unfortunately) and is meant to be used both in browsers and node environments. So basically I'm getting into the murky waters where both conditions are true, but because of the order it resolves to the wrong one.

**Comment by getify** [comment]
OK, thanks for the extra info. Will update the order of the `else if` statements at next library change.

**Comment by YaaL** [comment]
Thanks.

**Comment by joaovieira** [comment]
@getify https://github.com/umdjs/umd/commit/992cc0d071b7ebcd7feaad2a5349bdbeab09a0fe :)

**Pull request closed without merging**
